<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Samlgate</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Samlgate.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.101" />
  </ItemGroup>
</Project>
